### ISSUE TITLE
feature request -- restricting providers

### ISSUE THREAD

**Issue by ltd** [hellocoop/hello.dev#21]
This is far from a show stopper, but this is one of the scenarios  I was hoping to implement.  1) restrict the providers on the hello side to github, gitlab.  2) get the full  profile url, or repo name for which ever of the providers they picked.

**Comment by dickhardt** [comment]
The provider chosen is opaque to the developer => it does not make sense to restrict providers. The user has chosen a preferred provider they will use everywhere they use Hellō to access their cloud identity wallet.

We are adding Github and Gitlab as providers, as well as adding `github` and `gitlab` as claims that can be requested -- these would return the username & platform id for each of those providers. 

This brings up the question of optional claims. Reading between the lines, it seems your goal would be to get their profile for Github OR Gitlab. Correct?
