### ISSUE TITLE
A few possible typos on Feedback for “Hellō vs ____”

### ISSUE THREAD

**Issue by tfcarlin** [hellocoop/hello.dev#60]
Missing "s" on support? 

"Keyloak is a popular open source project written in Java that support all popular identity protocols including OAuth 2, OpenID Connect, SAML, SCIM, and LDAP."

Not sure about this one but it seems confusing.

"You no longer need to manage how the user linking their different accounts, or merging them."

I think you mean "use" in this sentence.

"In contrast, the user of passkeys is transparent to you if you use Hellō."

**Comment by dickhardt** [comment]
fixed with 86b7f349c839bee8241fc5026d877f10cd3c0239 -- thanks!
