### ISSUE TITLE
Broken Link: Next.js SDK Reference Points to Fastify Docs on Hello.dev Docs

### ISSUE THREAD

**Issue by rohilpinto** [hellocoop/hello.dev#63]
Hey there,

I noticed a potential issue in the Hello docs. While browsing the SDK references on [SDK](https://www.hello.dev/docs/sdks/) clicking the Next.js option seemed to redirect me to the Fastify documentation instead.

This sounds like a broken link.  Just wanted to give you a heads-up!

**Comment by rohanharikr** [comment]
Nice catch - fixed with 1e5e9b7ad9349960f04c2f73dc98c3ad56942916, thank you!
